phrase:
  access_token: 05b361ed2134f9051857db7bf17dae03467dbd2e3a3f7ee6798e53647d581b76
  project_id: 7700f497709834cfb6236b2b32de813b
  file_format: yml

  push:
    sources:
    - file: ./config/locales/<locale_name>.yml
    params:
      update_translations: true
  pull:
    targets:
    - file: ./config/locales/<locale_name>.yml
    
